server:
  port: 8082
  servlet:
    context-path: /v1/mallApp
spring:
  jackson:
    time-zone: GMT+8
    locale: zh_CN
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000  # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: -1ms      # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-idle: 10      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 5       # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
  mvc:
    throw-exception-if-no-handler-found: true
    locale-resolver: ACCEPT_HEADER
  session:
    storeType: REDIS
  aop:
    auto: true
  cache:
    type: EHCACHE
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    mode: HTML

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.example.mallapp.**.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

